### PR TITLE
HOPSWORKS-336

### PR DESCRIPTION
**Pull request by kouzant**
Remove custom highlight filter which name collides with the highligh module

https://hopshadoop.atlassian.net/browse/HOPSWORKS-336

### CODE REVIEW

**Comment by kouzant** [comment]
Then I think there is a namespace collision as a 'highlight' has been used at least here https://github.com/hopshadoop/hopsworks/blob/master/hopsworks-web/yo/app/views/createTopic.html#L59 way before Dela came in.

**Comment by kouzant** [comment]
I will rename it and update the PR.

**Comment by ErmiasG** [comment]
I think it should be named highlightUsername not highlightDela. It will highlight any thing that starts with @

**Comment by kouzant** [comment]
Done renaming to `highlightUsername`

**Pull request merged**
