### PR TITLE
Newfrontend security

### PR DESCRIPTION
**Pull request by ErmiasG**
2fa works fine now.

### CODE REVIEW

**Comment by jimdowling** [comment]
How did you fix the MessageBean -> SessionBean problem?

**Comment by jimdowling** [comment]
Can you have a look at the foreign keys that I had to disable to be able to create the tables? I am not sure why they are failing. Please fix before we merge. 
Also, what is the default login from rows.sql? admin@kth.se with password 'admin' didnt work.

**Comment by gholamiali** [comment]
This is strange. What errors do you get to create the tables?

In order to test the new development these steps must be done:
1. delete previous schemas for hopswroks 
2. cretae a new schema called hopsworks
3. run the rows.sql and test.sql 
4. create an email service using info in asadmin file in the root folder. note you need to have a valid gmail address and adopt the cli accordingly
5. pull the new changes in the CauthRealm and bulild it using the info in the README file.
6. there is a new table called variables which specifies the auth method (2fa and non 2fa) with true/false values. this can be updated on demand,
7.after theses steps you should be able to clean build and then run the platform
8.for non-2fa you can use admin@kth.se with password to login

If this is  not helping please let me know.

**Comment by gholamiali** [comment]
Now I even tried it on my machine: 

---------------------- 
DB Tables Results Through Running hopsworks.sql 
---------------------------

Executed successfully in 0.72 s, 0 rows affected.
Line 1, column 1

Executed successfully in 1.481 s, 0 rows affected.
Line 9, column 1

Executed successfully in 0.98 s, 0 rows affected.
Line 35, column 3

Executed successfully in 1.121 s, 0 rows affected.
Line 53, column 1

Executed successfully in 1.021 s, 0 rows affected.
Line 67, column 1

Executed successfully in 1.02 s, 0 rows affected.
Line 76, column 1

Executed successfully in 0.881 s, 0 rows affected.
Line 93, column 1

Executed successfully in 1.522 s, 0 rows affected.
Line 111, column 1

Executed successfully in 1.201 s, 0 rows affected.
Line 130, column 1

Executed successfully in 0.88 s, 0 rows affected.
Line 142, column 1

Executed successfully in 1.08 s, 0 rows affected.
Line 149, column 1

Executed successfully in 1.063 s, 0 rows affected.
Line 159, column 1

Executed successfully in 1.681 s, 0 rows affected.
Line 176, column 1

Executed successfully in 1.699 s, 0 rows affected.
Line 189, column 1

Executed successfully in 0.725 s, 0 rows affected.
Line 205, column 1

Executed successfully in 0.719 s, 0 rows affected.
Line 213, column 1

Executed successfully in 0.901 s, 0 rows affected.
Line 222, column 1

Executed successfully in 0.961 s, 0 rows affected.
Line 236, column 1

Executed successfully in 0.78 s, 0 rows affected.
Line 253, column 1

Executed successfully in 0.761 s, 0 rows affected.
Line 259, column 1

Executed successfully in 1.04 s, 0 rows affected.
Line 265, column 1

Executed successfully in 1.241 s, 0 rows affected.
Line 273, column 1

Executed successfully in 1.022 s, 0 rows affected.
Line 289, column 1

Executed successfully in 0.679 s, 0 rows affected.
Line 297, column 1

Executed successfully in 1.052 s, 0 rows affected.
Line 307, column 1

Executed successfully in 0.991 s, 0 rows affected.
Line 315, column 1

Executed successfully in 0.859 s, 0 rows affected.
Line 324, column 1

Executed successfully in 1.042 s, 0 rows affected.
Line 335, column 1

Executed successfully in 0.679 s, 0 rows affected.
Line 349, column 1

Executed successfully in 0.84 s, 0 rows affected.
Line 359, column 1

Executed successfully in 0.839 s, 0 rows affected.
Line 369, column 1

Executed successfully in 0.699 s, 0 rows affected.
Line 379, column 1

Executed successfully in 1.536 s, 0 rows affected.
Line 390, column 1

Executed successfully in 1.449 s, 0 rows affected.
Line 412, column 1

Executed successfully in 1.682 s, 0 rows affected.
Line 433, column 1

Executed successfully in 1.061 s, 0 rows affected.
Line 452, column 1

Executed successfully in 0.76 s, 0 rows affected.
Line 461, column 2

Executed successfully in 0.862 s, 0 rows affected.
Line 470, column 1

Executed successfully in 0.045 s, 0 rows affected.
Line 489, column 1

Executed successfully in 0.734 s, 0 rows affected.
Line 502, column 1

Executed successfully in 0.071 s, 0 rows affected.
Line 511, column 1

Executed successfully in 1.069 s, 0 rows affected.
Line 513, column 1

Execution finished after 41.449 s, 0 error(s) occurred.

--------------------------------

Authentication for user admin@kth.se Results

-----------------------


Info:   AuthExceptionMapper: class javax.ejb.AccessLocalException
Info:   AuthExceptionMapper: class javax.ejb.AccessLocalException
Info:   WebModule[null] ServletContext.log():email: admin@kth.se
Info:   WebModule[null] ServletContext.log():SESSIONID@login: 784a85b0508e7a59c9d8d315b47d
Info:   WebModule[null] ServletContext.log():SecurityContext: null
Info:   WebModule[null] ServletContext.log():SecurityContext in role: false
Info:   WebModule[null] ServletContext.log():USER: se.kth.hopsworks.model.Users[ uid=10000 ]
Info:   WebModule[null] ServletContext.log():1 step: admin@kth.se
Info:   WebModule[null] ServletContext.log():going to login. User status: 4
Info:   WebModule[null] ServletContext.log():3 step: admin@kth.se
Severe:   User agent --->>> Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:41.0) Gecko/20100101 Firefox/41.0
Info:   WebModule[null] ServletContext.log():SESSIONID: 784a8bfb4a106c8af2daa7d7afbd

**Comment by jimdowling** [comment]
Ali, on 2 different machines, I get the same problem with foreign key constraints. I commented out the offending rows, and it works, but i'd like to get the FKs back in. It looks like it's the project table that's the problem, and the users FK.

mysql> source /tmp/tables.sql
Query OK, 0 rows affected (0,15 sec)

Query OK, 0 rows affected (0,24 sec)

Query OK, 0 rows affected (0,18 sec)

Query OK, 0 rows affected (0,18 sec)

Query OK, 0 rows affected (0,18 sec)

Query OK, 0 rows affected (0,18 sec)

Query OK, 0 rows affected (0,21 sec)

ERROR 1215 (HY000): Cannot add foreign key constraint
ERROR 1215 (HY000): Cannot add foreign key constraint
ERROR 1215 (HY000): Cannot add foreign key constraint
ERROR 1215 (HY000): Cannot add foreign key constraint
Query OK, 0 rows affected (0,22 sec)

ERROR 1215 (HY000): Cannot add foreign key constraint
ERROR 1215 (HY000): Cannot add foreign key constraint
ERROR 1215 (HY000): Cannot add foreign key constraint
ERROR 1215 (HY000): Cannot add foreign key constraint
ERROR 1215 (HY000): Cannot add foreign key constraint
Query OK, 0 rows affected (0,23 sec)

Query OK, 0 rows affected (0,14 sec)

Query OK, 0 rows affected (0,16 sec)

Query OK, 0 rows affected (0,20 sec)

Query OK, 0 rows affected (0,24 sec)

Query OK, 0 rows affected (0,18 sec)

ERROR 1215 (HY000): Cannot add foreign key constraint
ERROR 1215 (HY000): Cannot add foreign key constraint
ERROR 1215 (HY000): Cannot add foreign key constraint
ERROR 1215 (HY000): Cannot add foreign key constraint
ERROR 1215 (HY000): Cannot add foreign key constraint
Query OK, 0 rows affected (0,16 sec)

Query OK, 0 rows affected (0,16 sec)

Query OK, 0 rows affected (0,14 sec)

Query OK, 0 rows affected (0,16 sec)

ERROR 1215 (HY000): Cannot add foreign key constraint
ERROR 1215 (HY000): Cannot add foreign key constraint
Query OK, 0 rows affected (0,28 sec)

Query OK, 0 rows affected (0,24 sec)

Query OK, 0 rows affected (0,16 sec)

Query OK, 0 rows affected (0,18 sec)

Query OK, 0 rows affected (0,01 sec)

Query OK, 0 rows affected (0,17 sec)

ERROR 1146 (42S02): Table 'hopsworks.project' doesn't exist
Query OK, 0 rows affected (0,20 sec)

**Comment by jimdowling** [comment]
Also, i am testing this on a NDB database. Are you running NDB, ali?

**Comment by gholamiali** [comment]
Yes, I use a NDB instance but I had not noticed why FK constraints are disabled in my system.

**Comment by gholamiali** [comment]
I enabled the FK constraints using "SET FOREIGN_KEY_CHECKS=1" but I could not reproduce the errors you get.

I have these settings: /usr/local/mysql/bin/mysql  Ver 14.14 Distrib 5.6.25-ndb-7.4.7, for linux-glibc2.5 (x86_64) using  EditLine wrapper

**Comment by jimdowling** [comment]
I'm using 7.4.8 of NDB. This is still a problem to be fixed, but i will merge now as we have other branches waiting on this one and we need to make progress. I will disable the broken FKs for now.

**Pull request merged**
